name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2.3.4

      - name: "Install Nix"
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: "Set up t2linux binary cache"
        if: "!contains(github.event.head_commit.message, '[no cache]')"
        uses: cachix/cachix-action@v10
        with:
          name: t2linux

      - name: "Build kernel, modules and firmware"
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: |
          ./build.sh

# vim: ft=yaml:et:sw=2:sts=2
